### ISSUE TITLE
Error after upgrading to v0.1.1

### ISSUE THREAD

**Issue by rdiazv** [masylum/mobx-rest-fetch-adapter#6]
Hi!
I'm getting this error after upgrading from 0.0.7 to 0.1.1 😞

```
assert.js?37e3:160 Uncaught (in promise) TypeError: util.inherits is not a function
```

**Comment by rdiazv** [comment]
Actually flow and almost all tests are failing. I would really hate to drop this library in favor of my own fork 😞... you could integrate TravisCI (or any alternative) to prevent merging broken pull requests 🙏 .

**Comment by masylum** [comment]
That was embarrassing! Added Travis and also released a new version that should fix it.
Thanks for your contributions.
